--insert into topic (id, name, description) values('cesar','cesars topic','cesars description');
--insert into topic (id, name, description) values('beata','beatas topic','beatas description');
--insert into course (id, topic_id, name, description) values ('kakor', 'cesar', 'goda kakor', 'kakor description')